name: assist
description: A new Flutter project.

publish_to: 'none'

# version history
# version: 883136.13447.1+46  - new version for test server to testflight- tejpal 17 nov
# version: 883136.1116.2+47   - date 27-11-2023
# version: 883136.1117.2+48   - date 29-11-2023
# version: 883136.1117.2+49   - date 30-11-2023
# version: 883136.1301.2+59   - date 22-07-2024
# version: 883136.1303.2+60   - date 24-07-2024
# version: 883136.1329.2+61   - date 23-01-2025 (maintenance & tiles hide work)
version: 883136.1329.3+63

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Firebase
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4

  # Storage & State
  get_storage: ^2.0.3
  get: ^4.6.5

  # Location
  geolocator: ^10.1.1
  location: ^5.0.3
  geocoding: ^2.0.5
  google_maps_flutter:

  # UI & Animation
  flutter_spinkit: ^5.1.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.5
  horizontal_data_table: ^4.1.4
  sliding_up_panel: ^2.0.0+1
  convex_bottom_bar: ^3.1.0+1
  carousel_slider: ^5.0.0

  # Utils
  intl: ^0.18.1
  http: ^1.2.1
  uuid: ^4.5.1
  url_launcher: ^6.1.7
  sms_autofill: ^2.3.0
  dropdown_search: ^5.0.5
  webview_flutter: ^4.0.7
  connectivity_plus:
  flutter_local_notifications: ^19.5.0
  package_info_plus: ^9.0.0
  flutter_polyline_points: ^3.1.0
  permission_handler: ^10.2.0
  image_picker: ^1.0.4
  flutter_inappwebview: ^6.1.5
  syncfusion_flutter_pdfviewer: ^29.1.38
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  local_auth: ^2.1.6
  slide_countdown: ^0.6.0
  flutter_credit_card: ^3.0.7
  credit_card_form: ^0.0.7
  timezone: ^0.10.0
  flutter_screenutil: ^5.9.3
  pinput: ^3.0.1
  otp_autofill: 4.1.0
  another_flushbar: ^1.12.30
  in_app_update: ^4.2.3
  dio:

  # Local pusher client
  pusher_client:
    path: C:/Users/91725/OneDrive/Documents/pusherClient_somya

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/fonts/Avenir-Black_0.ttf
          weight: 700
        - asset: fonts/fonts/Avenir-Medium.ttf
          weight: 300
